
/* Drop Tables */

DROP TABLE IF EXISTS CONTACT_TEL_DETAIL;
DROP TABLE IF EXISTS CONTACT;




/* Create Tables */

CREATE TABLE CONTACT
(
	ID serial NOT NULL,
	FIRST_NAME varchar(60),
	LAST_NAME varchar(40),
	BIRTH_DATE date,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE CONTACT_TEL_DETAIL
(
	ID serial NOT NULL,
	CONTACT_ID int,
	TEL_TYPE varchar(20),
	TEL_NUMBER varchar(20),
	PRIMARY KEY (ID)
) WITHOUT OIDS;



/* Create Foreign Keys */

ALTER TABLE CONTACT_TEL_DETAIL
	ADD FOREIGN KEY (CONTACT_ID)
	REFERENCES CONTACT (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



