
/* Drop Tables */

DROP TABLE IF EXISTS CONTACT_TEL_DETAIL;
DROP TABLE IF EXISTS CONTACT_HOBBY_DETAIL;
DROP TABLE IF EXISTS CONTACT;
DROP TABLE IF EXISTS HOBBY;




/* Create Tables */

CREATE TABLE CONTACT
(
	ID serial NOT NULL,
	FIRST_NAME varchar(60),
	LAST_NAME varchar(40),
	BIRTH_DATE date,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE CONTACT_HOBBY_DETAIL
(
	CONTACT_ID int NOT NULL,
	HOBBY_ID varchar(20) NOT NULL
) WITHOUT OIDS;


CREATE TABLE CONTACT_TEL_DETAIL
(
	ID serial NOT NULL,
	CONTACT_ID int,
	TEL_TYPE varchar(20),
	TEL_NUMBER varchar(20),
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE HOBBY
(
	HOBBY_ID varchar(20) NOT NULL,
	PRIMARY KEY (HOBBY_ID)
) WITHOUT OIDS;



/* Create Foreign Keys */

ALTER TABLE CONTACT_TEL_DETAIL
	ADD FOREIGN KEY (CONTACT_ID)
	REFERENCES CONTACT (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CONTACT_HOBBY_DETAIL
	ADD FOREIGN KEY (CONTACT_ID)
	REFERENCES CONTACT (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CONTACT_HOBBY_DETAIL
	ADD FOREIGN KEY (HOBBY_ID)
	REFERENCES HOBBY (HOBBY_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



